chore(lib): Updated url with the
canonical/redis-k8s-operator pull request #100
Opened 2024-10-14 11:52 UTC by alithethird

## Issue

Since [[DPE-5200] add leader info to relation data](https://github.com/canonical/redis-k8s-operator/pull/96) we need to update a lot of our(IS DevOps) charms to use the `leader-host`. We also use the `.url` property but since it uses the unit ip we have to construct it in the charm. 
## Solution
Constructing the `.url` property in the library instead of changing multiple number of charms.

2024-10-23 10:22 UTC, reneradoi commented
Hello @alithethird , I tried to look into the issue with the failed integration test. It is failing in the build-step, probably because of the change to the lib. Unfortunately I cannot really debug that without cloning your private repo. Could you please create a branch on this repo here, and push your changes to this new branch? We can also have a session together if that would help you, just let me know.

2024-10-23 10:26 UTC, alithethird commented
Hi @reneradoi ! Thank you! I can not create a branch because I do not have write access. My fork should be private but just in case I added you as a collaborator to the fork.

2024-10-27 17:10 UTC, reneradoi requested changes
Hey @alithethird, in general we'd be fine with adjusting this, as long as the interface stays the same. But after looking at the failing test, I don't think that this is flaky as you mentioned earlier. I have run the integration tests against the main branch on multiple tries, and there was no failure.

The error from the CI pipeline is [here](https://github.com/canonical/redis-k8s-operator/actions/runs/11340535060/job/31940363754?pr=100#step:6:146). I suggest you check this and adjust your code accordingly.

2024-11-08 15:03 UTC, reneradoi commented
@alithethird After debugging with a local deployment, I've found the cause of the failing tests and fixed it by updating the pylibjuju to a newer version. Tests are now stable again. Furthermore I've adjusted the logic for the lib changes a little to make them more robust. Please have another look if this is fine for you.

2024-11-08 15:04 UTC, reneradoi approved these changes

2024-11-08 15:51 UTC, Mehdi-Bendriss approved these changes
Thanks! Left a minor comment

2024-11-08 15:51 UTC, Mehdi-Bendriss commented on lib/charms/redis_k8s/v0/redis.py
> +        if app_data:
```suggestion
        if not (relation_data := self.relation_data):
            return None
            
        redis_host = relation_data.get("hostname")

        if app_data := self.app_data:
```

2024-11-08 17:13 UTC, alithethird reviewed
Looks great! Thanks a lot for your time.

2024-11-11 07:32 UTC, merged