Tests and CI update
canonical/redis-k8s-operator pull request #17
Opened 2022-03-07 17:00 UTC by zmraul

This PR updates the remaining parts to follow the operator template.
- Migrate testing to tox
- Fix linting
- Remove old testing files
- Update documentation to reflect changes

2022-03-08 08:45 UTC, edumucelli commented on .github/workflows/python-package.yml
> -# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
Why no more Github actions? This is completely unrelated to the changes for a sidecar approach, or am I missing something here?

2022-03-08 08:45 UTC, edumucelli commented on .flake8
> -[flake8]
Why this was removed, how it is related to the sidecar change?

2022-03-08 08:52 UTC, edumucelli commented
> This PR updates the remaining parts to follow the operator template.
> 
>     * Migrate testing to tox
> 
>     * Fix linting
> 
>     * Remove old testing files
> 
>     * Update documentation to reflect changes

I am not familiar with the sidecar approach, but it seems there are plenty of unrelated changes in this PR. I'd suggest making the needed changes for the sidecar and then another PR for what is not.

2022-03-08 09:07 UTC, zmraul commented
Hi Eduardo! I understand the title can lead to confusion, I can change it to just `template update` if that is the case. As you said, the changes here don't really affect anything sidecar related.

This PR updates the testing and CI to follow the [operator-template](https://github.com/canonical/operator-template).

These and following changes will target the `update` branch, which is related, but not limited to the sidecar update. This way we can work on features/fixes while keeping `main` as it is right now. Does this sound good? or should I do it some other way.

2022-03-08 09:12 UTC, WRFitch requested changes
Needs a couple of small changes, but otherwise lgtm

2022-03-08 09:12 UTC, WRFitch commented on .github/workflows/ci.yaml
> +          # TEMPLATE-TODO: Replace the application name
Since you've already done this, you can remove this comment

2022-03-08 09:12 UTC, WRFitch commented on tests/test_charm.py
>  class TestCharm(TestCase):
Could you please move this file to tests/integration/test_charm.py?

2022-03-08 09:17 UTC, edumucelli commented
> Hi Eduardo! I understand the title can lead to confusion, I can change it to just `template update` or something else if that is the case. As you said, the changes here don't really affect anything sidecar related.
> 
> This PR updates the testing and CI to follow the [operator-template](https://github.com/canonical/operator-template).
> 
> These and following changes will target the `update` branch, which is related, but not limited to the sidecar update. This way we can work on features/fixes while keeping `main` as it is right now. Does this sound good? or should I do it some other way.

I see, I was not aware there was a template, and that tests and ci were guided by it as well. Sure, it is good, go ahead.

2022-03-08 09:17 UTC, edumucelli approved these changes

2022-03-08 09:30 UTC, zmraul commented on tests/test_charm.py
>  class TestCharm(TestCase):
Yes! Thanks for catching that.
PS: It will be tests/**unit**/test_charm.py

2022-03-08 09:53 UTC, WRFitch approved these changes

2022-03-08 09:56 UTC, WRFitch commented on tests/test_charm.py
>  class TestCharm(TestCase):
Yes, it is - sorry, thanks for catching that!

2022-03-08 13:43 UTC, pengale reviewed
Overall, this looks good, and represents a nice update to the current charm template.

The doc strings are very generic, though, and this is a great opportunity to make them a bit more specific.

2022-03-08 13:43 UTC, pengale commented on src/charm.py
> +
This is an opportunity to talk a little bit about what this charm does. Obviously, this class is the core charm for the service. But what does it currently do, specifically? Is there anything that someone editing this class might need to know?

2022-03-08 13:43 UTC, pengale commented on src/charm.py
> +        """Handle config_changed event."""
Again, this could use a descriptive docstring. Something that would work better might be:

"Possibly update the container.

On config changed, check to see if we need to update the container contents. If we do, update and restart the redi service."

2022-03-08 13:43 UTC, pengale commented on src/charm.py
> +        """Handle update_status event."""
Same here, as far as docs go.

"On update status, check the container."

2022-03-08 13:43 UTC, pengale commented on src/charm.py
> +        """Handle for check_service action."""
And here: "When requested, check service."

2022-03-09 10:58 UTC, zmraul commented
> Overall, this looks good, and represents a nice update to the current charm template.
> 
> The doc strings are very generic, though, and this is a great opportunity to make them a bit more specific.

Hi @pengale, I agree with all you said. I've added a bit of explanation to each docstring. However, I've been working on a follow up PR that will refactor several parts of the code, to prepare for new features like replication. So these docstrings might get changed pretty soon :)

2022-03-10 18:07 UTC, pengale approved these changes
Nice changes to the docs. +1 :-)

2022-03-10 19:53 UTC, marceloneppel approved these changes
Great PR @zmraul! I just left one question about the `git` build package.

2022-03-10 19:53 UTC, marceloneppel commented on charmcraft.yaml
> +      - git
Do you need `git` for some dependency? I saw that the repo no longer uses git dependencies (like `git+https://github.com/juju-solutions/resource-oci-image#egg=oci-image`).

2022-03-16 11:17 UTC, zmraul commented on charmcraft.yaml
> +      - git
I don't, thanks for letting me know! Some leftovers from the template :)

2022-03-16 14:19 UTC, merged