DPE-117 Aadd password action
canonical/redis-k8s-operator pull request #21
Opened 2022-03-25 15:36 UTC by zmraul

### Problem

This PR address JIRA ticket [DPE-117](https://warthogs.atlassian.net/browse/DPE-117).
When deploying the database with a default password, an action should be provided to retrieve that password.
 
### Solution

The charm will implement an action to return the initial password.

### Context

This charm stores the password on the peer relation databag.

### Release Notes

- `actions.yaml`: new action created; `get-initial-admin-password`
- `src/charm.py`
   - `_get_password_action()`:  Handler for the action. Will create a result with the key `redis-password`.
- `tests/integration/test_charm.py`
   - `test_application_is_up()`: now uses the password
   - `test_database_with_no_password()`: check that the database is not accessible without a password
   - `test_same_password_after_scaling()`: scale down and up the application to test that the password remains the same

2022-03-25 16:02 UTC, WRFitch requested changes
Looks good, some notes about your tests

2022-03-25 16:02 UTC, WRFitch commented on tests/integration/test_charm.py
> +        assert True
You can rewrite this to be more terse: 
```python
with pytest.raises(AuthenticationError):
    cli.ping()
```

2022-03-25 16:02 UTC, WRFitch commented on tests/integration/test_charm.py
> +    assert cli.ping()
I understand that we need this action to access the password and therefore create the Redis object, but it makes it less clear that this test tests database access, since it will fail if the `get-initial-admin-password` action fails. Could this action be tested separately, or at least given an explicit assertion in this test to ensure the reason for possible failures is communicated to the developer?

2022-03-25 16:11 UTC, marceloneppel reviewed
LGTM Raúl! One note in the integration tests.

2022-03-25 16:11 UTC, marceloneppel commented on tests/integration/test_charm.py
> +    after_pw = (await action.wait()).results["redis-password"]
You can create a helper method to encapsulate the logic of calling the action to avoid duplication.

2022-03-25 17:34 UTC, shayancanonical approved these changes
LGTM, but support the already existing comments on the PR

2022-03-28 10:06 UTC, zmraul commented on tests/integration/test_charm.py
> +        assert True
Thanks for the suggestion! Added :)

2022-03-28 10:10 UTC, zmraul commented on tests/integration/test_charm.py
> +    assert cli.ping()
In this case, the password will be either a correct string or an empty string. If the password is not correct, the test will fail regardless with an AuthenticationError. Maybe a debug log with the retrieved password?

2022-03-28 10:11 UTC, zmraul commented on tests/integration/test_charm.py
> +    after_pw = (await action.wait()).results["redis-password"]
Yes! I extracted the code into a helper method.

2022-03-28 10:25 UTC, WRFitch commented on tests/integration/test_charm.py
> +    assert cli.ping()
My point was more that they're separate functions and should therefore be tested separately, similar to how unit tests work. However, the test and the action are both simple enough that it's not a big deal, especially if you add some extra logging.

2022-03-28 10:25 UTC, WRFitch approved these changes

2022-03-28 11:02 UTC, marceloneppel approved these changes

2022-03-29 08:05 UTC, merged