Add integration tests with pytest-operator
canonical/redis-k8s-operator pull request #26
Opened 2022-04-08 09:57 UTC by lferran

2022-04-08 10:01 UTC, lferran commented on requirements.txt
> +jinja2~=2.11
3.x version of Jijna2 aren't supported by the charm-helpers lib: https://github.com/juju/charm-helpers/blob/master/requirements.txt#L7-L10

2022-04-08 13:04 UTC, lferran commented on charmcraft.yaml
> +      - markupsafe
I had to add this here, otherwise I was getting the following error while building with charmcraft
```
      File "/tmp/pip-install-x18ee6cd/Jinja2/src/jinja2/__init__.py", line 8, in <module>
        from .environment import Environment as Environment
      File "/tmp/pip-install-x18ee6cd/Jinja2/src/jinja2/environment.py", line 14, in <module>
        from markupsafe import Markup
    ModuleNotFoundError: No module named 'markupsafe'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command o
utput.
```
I'm unsure if that is the best way to fix it.

2022-04-08 13:39 UTC, zmraul requested changes
Nice Job! This is a good addition :) I left a couple of minor comments.

2022-04-08 13:39 UTC, zmraul commented on charmcraft.yaml
> +      - markupsafe
I remember this issue from a while back. See [here](https://discourse.charmhub.io/t/install-or-update-python-packages-before-packing-a-charm/5158). Maybe try adding [setuptools] as a better fix?

2022-04-08 13:39 UTC, zmraul commented on DEVELOPMENT.md
> +    tox -e integration
The `tox.ini` file has all testenv from the template (`[testenv:lint], [testenv:fmt] ...`). You can pretty much copy the docs from the [operator template](https://github.com/canonical/template-operator/blob/main/CONTRIBUTING.md#testing) here.

2022-04-08 15:13 UTC, zmraul approved these changes

2022-04-08 15:18 UTC, lferran commented on charmcraft.yaml
> +      - setuptools == 57.5.0
This version is needed due to Tempita package still requiring `2to3`. Setuptools dropped support for `2to3` at `57.5.0` version: https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v5800

Hopefully Tempita is not used in the future, as it seems to be unmaintained.

2022-04-11 07:50 UTC, lferran commented
Thanks for the review! Ready to be merged? Feel free to do so, as I don't have merge permissions.

2022-04-11 11:18 UTC, paulomach commented on charmcraft.yaml
> +      - setuptools == 57.5.0
nit: Add new line

2022-04-11 11:20 UTC, paulomach approved these changes
LGTM, small nit

2022-04-11 11:21 UTC, paulomach commented
@zmraul , i think this repo is allowing merge without minimal 2 approvals. Should it be changed?

2022-04-11 11:43 UTC, zmraul commented
> @zmraul , i think this repo is allowing merge without minimal 2 approvals. Should it be changed?

I don't think I have access to change this. Maybe @edumucelli @mthaddon can help?

2022-04-11 11:51 UTC, shayancanonical commented on .github/workflows/python-package.yml
> +          app: redis-k8s
nit: add new line please

2022-04-11 12:27 UTC, edumucelli commented
> > @zmraul , i think this repo is allowing merge without minimal 2 approvals. Should it be changed?
> 
> I don't think I have access to change this. Maybe @edumucelli @mthaddon can help?

Everyone in the `data-platform` or ``data-platform-admins` groups has `admin` access to this repo, so I'd go towards managing per-group than per-person rights. I'd suggest asking the manager of those groups to add the respective people.

2022-04-11 12:34 UTC, jnsgruk commented
> > > @zmraul , i think this repo is allowing merge without minimal 2 approvals. Should it be changed?
> > 
> > 
> > I don't think I have access to change this. Maybe @edumucelli @mthaddon can help?
> 
> Everyone in the `data-platform` or `data-platform-admins` groups has `admin` access to this repo, so I'd go towards managing per-group than per-person rights. I'd suggest asking the manager of those groups to add the respective people.

Fixed :)

2022-04-11 12:59 UTC, lferran commented on .github/workflows/python-package.yml
> +          app: redis-k8s
👍🏼 done! out of curiosity: why the new line needed?

2022-04-11 13:17 UTC, paulomach commented on .github/workflows/python-package.yml
> +          app: redis-k8s
AFAIK, this originated from old compilers having trouble parsing last lines missing CRLF.
Nowadays it's just a nice practice to keep all lines in the file consistent.

2022-04-19 11:04 UTC, shayancanonical approved these changes
LGTM, but left a minor nit that could be ignored if irrelevant

2022-04-19 11:04 UTC, shayancanonical commented on .github/workflows/python-package.yml
> +
why the empty lines on line 48 and 51?

2022-04-19 11:24 UTC, lferran commented on .github/workflows/python-package.yml
> +
indeed, they are not necessary. It's a habit I have - adding newlines sometimes helps me isolating parts of the code from each other (in this case, steps).

2022-04-20 09:16 UTC, merged