DPE-485 Scale down
canonical/redis-k8s-operator pull request #39
Opened 2022-07-15 09:21 UTC by zmraul

# Issue

This PR addresses Jira ticket [DPE-485](https://warthogs.atlassian.net/browse/DPE-485).
Logic for scaling-down has been added.

## Solution

During scale-down, new quorum will be propagated and a reset command will be sent to all sentinels, so they remove information form departing `redis-server` and `sentinel`.
- In the event of one of the departing units being the current replication master, a manual failover will be triggered, so a new master is elected.

## Context

Some changes have been made to the initial command. The initial replication master needs replica flags as well. When a failover occurs, the old master will need those flags so it can become a secondary successfully.

## Release Notes

## Testing

2022-07-19 13:00 UTC, WRFitch approved these changes
LGTM, one small note about waits in testing.

2022-07-19 13:00 UTC, WRFitch commented on tests/integration/test_charm.py
> +    time.sleep(3)
Is this necessary, given that the next command is another wait?

2022-07-19 13:02 UTC, zmraul commented on tests/integration/test_charm.py
> +    time.sleep(3)
The issue is that querying info (`"SENTINEL MASTER redis-k8s"`) right after issuing the `failover` command can result on info not being updated yet. Meaning that the next block passes immediately, and the `role` assert might fail.

2022-07-19 15:24 UTC, MiaAltieri requested changes

2022-07-19 15:24 UTC, MiaAltieri commented on src/charm.py
>                  "Initial replication, setting leader-host to {}".format(self.unit_pod_hostname)
I might have missed the PR where current_master was added, but I think tracking the master is a controversial practice 🤷 but idc

2022-07-19 15:24 UTC, MiaAltieri commented on src/charm.py
> +        else:
nit: (do this if you want or ignore) 
code might look nicer if you do:
```
        if not self._get_password():
            logger.info("Creating password for application")
            self._peers.data[self.app][PEER_PASSWORD_KEY] = self._generate_password()
        if not self.get_sentinel_password():
            logger.info("Creating sentinel password")
            self._peers.data[self.app][SENTINEL_PASSWORD_KEY] = self._generate_password()
        if self.current_master is None:
            logger
            self._peers
             return 
        
        # code for a new leader being elected 
        # TODO extract to method shared with relation_departed
            self._update_application_master()
            self._update_quorum()
            try:
                self._is_failover_finished()
            except (RedisFailoverCheckError, RedisFailoverInProgressError):
                logger.info("Failover didn't finish, deferring")
                event.defer()
                return

            logger.info("Resetting sentinel")
            self._reset_sentinel()
```

2022-07-19 15:24 UTC, MiaAltieri commented on src/charm.py
> +                raise
since you're not doing anything with RedisError I am pretty sure you can just do 
```suggestion
sentinel.execute_command(f"SENTINEL FAILOVER {self._name}")
```

2022-07-19 15:24 UTC, MiaAltieri commented on src/sentinel.py
> +        if not container.exists(CONFIG_DIR):
maybe include a comment about the bug to update this code later? but idk I dont see much wrong with having a mkdir and then a push (instead of just a push (once they fix the bug))

2022-07-19 15:27 UTC, MiaAltieri reviewed
looking good!

2022-07-19 21:01 UTC, paulomach approved these changes
Just some nits

2022-07-19 21:01 UTC, paulomach commented on src/charm.py
>                  "Initial replication, setting leader-host to {}".format(self.unit_pod_hostname)
Indeed. To be on the safe side, the best would be update the master right before the test, if feasible.

2022-07-19 21:01 UTC, paulomach commented on src/charm.py
> +        if not self.unit.is_leader():
what would happen when the leader is the departing unit?

2022-07-19 21:01 UTC, paulomach commented on src/charm.py
> +        if info is None:
nit:

```suggestion
        if not info:
```

2022-07-19 22:13 UTC, marcoppenheimer commented on src/charm.py
> +        """Try to failover the current master."""
I would add to the docstring that this is a 'leader-only' function.

2022-07-19 22:13 UTC, marcoppenheimer commented on src/charm.py
>                      logger.error("Error connecting to instance: {} - {}".format(hostname, e))
What happens to cause these exceptions to be raised? Do we expect this method call to fail silently?

2022-07-19 22:13 UTC, marcoppenheimer commented on tests/integration/test_charm.py
> +async def test_scale_down_departing_master(ops_test: OpsTest):
Possibly related to my other question. 
Is there value in having a test where we scale down the current Juju leader, which is also the current quorum leader?

2022-07-19 22:13 UTC, marcoppenheimer commented on tests/unit/test_charm.py
> +
Massively unhelpful suggestion. But for these sorts of mappings, I find it readable to do:


```suggestion
mapping = {
    "ROLE": ["non-master"],
    f"SENTINEL CKQUORUM {self.harness.charm._name}": "OK",
    f"SENTINEL MASTER {self.harness.charm._name}": ["ip", "different-leader"],
}

return mapping.get(str, "??")

```

2022-07-20 07:39 UTC, zmraul commented on src/charm.py
>                  "Initial replication, setting leader-host to {}".format(self.unit_pod_hostname)
`current_master` is used here as a way to know that the application is being deployed for the first time. Once is set, relation events will query sentinel to check if the application data is good, and update if they don't match.

2022-07-20 07:42 UTC, zmraul commented on src/charm.py
> +                raise
Yeah I was on the fence about making it explicit or not. I'll remove it since `RedisError` is being handled on the calling method.

2022-07-20 07:48 UTC, zmraul commented on src/charm.py
> +        if info is None:
I think I'll leave it as `if x is None` because that's an explicit return from `get_master_info()` when something wrong happens.

2022-07-20 07:54 UTC, zmraul commented on src/charm.py
>                      logger.error("Error connecting to instance: {} - {}".format(hostname, e))
The problem is that I need to broadcast commands to all sentinels. But that includes sentinels that are gone on scaling down operations (when querying units in the relation you get departing units as well).

2022-07-20 08:14 UTC, zmraul commented on src/charm.py
> +        else:
formatting might be messed up?

2022-07-20 08:20 UTC, zmraul commented on src/charm.py
> +        if not self.unit.is_leader():
So, chances are that sentinel will do a failover on its own, since juju leader will take some time to execute. If juju leader reelection is super fast, the downside is that sentinels will not have a proper reset. The quorum will be correctly updated, which is a more critical part of the failover process.
It's not a big deal, specially in k8s. It only means that they store a pointer to a hostname that is no longer there. I could do a check on master info, to see if the flag `o_down` (objective down, meaning that sentinels have reached quorum and agree that the master is down) is there and force a failover immediately.

2022-07-20 08:28 UTC, zmraul commented on tests/integration/test_charm.py
> +async def test_scale_down_departing_master(ops_test: OpsTest):
I would love to add this. Is there an example somewhere on how to test this condition consistently?

2022-07-20 10:57 UTC, paulomach commented on tests/unit/test_charm.py
> +
I like that!

2022-07-20 12:04 UTC, shayancanonical approved these changes

2022-07-20 16:51 UTC, marceloneppel approved these changes

2022-07-20 16:51 UTC, marceloneppel commented on src/exceptions.py
> +    """Exception raised when creating a user fails."""
Does it really happen when creating a user fails or the description should be changed?

2022-07-21 07:14 UTC, zmraul commented on src/exceptions.py
> +    """Exception raised when creating a user fails."""
Maybe I copied the exception layout from the Mysql charm, and maybe I forgot to update this description. :eyes:

2022-07-21 09:02 UTC, merged