Redis relation integration tests
canonical/redis-k8s-operator pull request #40
Opened 2022-07-22 10:59 UTC by zmraul

2022-08-02 09:03 UTC, delgod commented on tox.ini
> +[testenv:integration-redis]
maybe better name 
```suggestion
[testenv:integration-relation]
```

2022-08-04 07:59 UTC, MiaAltieri requested changes

2022-08-04 07:59 UTC, MiaAltieri commented on tests/integration/test_redis_relation.py
> +    async with ops_test.fast_forward():
I wonder if your failures have to do with `async with ops_test.fast_forward()`, what happens if you remove it?

2022-08-04 07:59 UTC, MiaAltieri commented on tests/integration/test_redis_relation.py
> +    await ops_test.model.wait_for_idle(
nit
```suggestion
    # discourse is in blocked state until relations are added.
    await ops_test.model.wait_for_idle(
```

2022-08-04 07:59 UTC, MiaAltieri commented on tests/integration/test_redis_relation.py
> +async def test_discourse(ops_test: OpsTest):
nit
```suggestion
async def test_discourse_relation(ops_test: OpsTest):
```

2022-08-04 07:59 UTC, MiaAltieri commented on tests/integration/test_redis_relation.py
> +async def test_discourse_request(ops_test: OpsTest):
might be good to test some CRUD ops here

2022-08-04 07:59 UTC, MiaAltieri commented on tests/integration/test_redis_relation.py
> +async def test_discourse_from_discourse_charmers(ops_test: OpsTest):
Sorry I am a newb, why are there two discourse checks?

2022-08-04 07:59 UTC, MiaAltieri commented on tests/integration/test_redis_relation.py
> +    )
I think you mentioned that legacy relations turn off Auth might be good to add these tests:
test_redis_auth_disabled
test_add_unit_joins_without_auth
test_new_relation_fails_with_legacy (new relations need auth and shouldn't be able to join)
test_legacy_relation_fails_with_new (if app is related to a new app a legacy relation shouldn't be able to turn off auth for everyone)

2022-08-04 07:59 UTC, MiaAltieri commented on tests/integration/test_redis_relation.py
> +    )
feel free to do that in a separate PR

2022-08-04 07:59 UTC, MiaAltieri commented on tests/integration/test_redis_relation.py
> +    )
add a test for expected relation data: test_relation_data

2022-08-04 07:59 UTC, MiaAltieri commented on tests/unit/test_charm.py
> +            WaitingStatus("Waiting for Pebble in sentinel container"),
nit: `self.assertTrue(isinstance(self.harness.charm.unit.status, WaitingStatus))` this way tests don't fail whenever you change the status name :)

2022-08-04 09:31 UTC, zmraul commented on tests/integration/test_redis_relation.py
> +    async with ops_test.fast_forward():
No problem with this test, the failures are always on the `test_discourse_request` test.

2022-08-04 09:32 UTC, zmraul commented on tests/integration/test_redis_relation.py
> +async def test_discourse_from_discourse_charmers(ops_test: OpsTest):
Two discourse charms on charmhub using the legacy lib.

2022-08-08 12:55 UTC, zmraul commented on tests/integration/test_redis_relation.py
> +async def test_discourse_request(ops_test: OpsTest):
Redis is not used as a storage for things related to the API (users, posts, responses...), all that goes into postgresql. Discourse will be unresponsive if redis is not working, so I think querying the `site.json` should cover discourse working.

2022-08-08 12:56 UTC, zmraul commented on tests/integration/test_redis_relation.py
> +    )
Similar to the previous comment, if relation data is wrong, discourse won't be available, so I think relation data is covered indirectly by a correct deployment.

2022-08-08 18:46 UTC, paulomach approved these changes
lgtm, some nits here and there

2022-08-08 18:46 UTC, paulomach commented on lib/charms/redis_k8s/v0/redis.py
>          if not self.model.unit.is_leader():
remove comment?

2022-08-08 18:46 UTC, paulomach commented on tests/integration/helpers.py
> +    proc = subprocess.check_output(f"juju status --model={model_name}".split())
Did you explore using `--format=json|yaml` to ease parsing output? (afaik, it can be harder)

2022-08-08 18:46 UTC, paulomach commented on tests/integration/test_redis_relation.py
> +    await ops_test.model.add_relation(
warning: prefer `relate` over `add_relation` since it's deprecated on going away eventually. Syntax is the same

2022-08-08 20:31 UTC, marceloneppel commented
LGTM!

2022-08-08 21:56 UTC, marcoppenheimer approved these changes

2022-08-09 00:18 UTC, marceloneppel approved these changes

2022-08-09 07:12 UTC, zmraul commented on tests/integration/helpers.py
> +    proc = subprocess.check_output(f"juju status --model={model_name}".split())
This is here more or less for the same reason as Mia did last week. Status in this situation is unreliable, once that is fixed this code should go away.

2022-08-09 07:23 UTC, MiaAltieri approved these changes
Great work Raul!! 🤩

2022-08-09 08:44 UTC, merged