COS integration
canonical/redis-k8s-operator pull request #61
Opened 2022-11-30 15:23 UTC by zmraul

This PR shows how a DB specific exporter and some default dashboards can be added to a charm.

Since this is a k8s charm, the exporter has been added as an extra container to the deployment. Ideally, exporters will come packed with the workload container (specifically node and process exporter).

2024-05-22 14:34 UTC, reneradoi submitted a review, later dismissed

2024-06-04 14:17 UTC, reneradoi commented
This PR is now ready for review.

2024-06-04 14:44 UTC, delgod requested changes

2024-06-04 14:44 UTC, delgod commented on metadata.yaml
> +    upstream: docker.io/oliver006/redis_exporter:v1.59.0
Yes, it is the right thing in most cases, but I believe we should control all the artefacts in Canonical solutions.
Could we please add the exporter into your image, without using 3rd party image?
(in such a case, the additional resource and side-car(layer) are not needed).

2024-06-05 14:50 UTC, MiaAltieri requested changes
Looks great! +1 to Mykolas earlier point

And if possible can you add a test suite similar to [this one](https://github.com/canonical/mongodb-k8s-operator/blob/6/edge/tests/integration/metrics_tests/test_metrics.py)? A separate PR would also be fine

2024-06-05 14:50 UTC, MiaAltieri commented on src/charm.py
> +                            "targets": ["*:9121"],
nit constant

2024-06-05 14:50 UTC, MiaAltieri commented on src/charm.py
> +                group="redis",
nit const for "redis" too (if its too annoying feel free to ignore)

2024-06-05 14:50 UTC, MiaAltieri commented on src/redis_exporter.py
> +                        "REDIS_PASSWORD": self.charm._get_password(),
since this relies on the charm password, we must be sure that we make a call to `_update_exporter_layer ` on password change events (if the charm handles them)

2024-06-07 11:23 UTC, reneradoi commented on src/charm.py
> +                            "targets": ["*:9121"],
done

2024-06-07 11:26 UTC, reneradoi commented on src/charm.py
> +                group="redis",
done

2024-06-11 12:43 UTC, reneradoi commented on metadata.yaml
> +    upstream: docker.io/oliver006/redis_exporter:v1.59.0
This charm now uses the [charmed-redis-rock](https://github.com/canonical/charmed-redis-rock/blob/main/rockcraft.yaml), which includes the `redis_exporter` binary based on [this fork](https://github.com/canonical/redis_exporter/tree/v1.60.0) of the original code.

2024-06-11 12:46 UTC, reneradoi commented on src/redis_exporter.py
> +                        "REDIS_PASSWORD": self.charm._get_password(),
This charm does not handle passwort changes, so no need for action here.

2024-06-11 15:26 UTC, MiaAltieri reviewed
Looks great! Do you plan to add integrations tests in this PR or in a future one?

2024-06-11 15:26 UTC, MiaAltieri commented on src/charm.py
>      PEER,
Note for future Redis developers, this will grow and slowly become huge, maybe in the future it will be worth it to have a constant's "class" that way you can do things like `Constants.METRICS_PORT ` instead of importanting all of the constants.

Obv not a priority at all, but maybe a nice task for a future onboarder or a quick clean up task

2024-06-11 15:26 UTC, MiaAltieri commented on metadata.yaml
> +    upstream: ghcr.io/canonical/charmed-redis:7.2.5-22.04-edge
🥳 nice work

2024-06-11 18:52 UTC, delgod approved these changes

2024-06-12 06:51 UTC, reneradoi commented
> And if possible can you add a test suite similar to [this one](https://github.com/canonical/mongodb-k8s-operator/blob/6/edge/tests/integration/metrics_tests/test_metrics.py)? A separate PR would also be fine

I've added some test coverage for the metrics exporter here: https://github.com/canonical/redis-k8s-operator/blob/39b9098effd5194320d039486f39163d07334d3c/tests/integration/test_charm.py#L86-L98

2024-06-12 07:50 UTC, MiaAltieri approved these changes
Thank you Rene!

2024-06-12 10:27 UTC, Mehdi-Bendriss reviewed
Thanks René, I have a minor comment on the README

2024-06-12 10:27 UTC, Mehdi-Bendriss commented on DEVELOPMENT.md
> +    juju run redis-k8s/0 get-initial-admin-password --wait
we unfortunately need to rollback this change (and the ones after it), because we currently offer the Redis charm fir juju `2.9.x` and `juju run-action`  only got renamed in 3.x

2024-06-12 10:30 UTC, reneradoi commented on DEVELOPMENT.md
> +    juju run redis-k8s/0 get-initial-admin-password --wait
Oh ok, I didn't know that, just changed this on the fly because my juju client complained when I pasted the commands.

2024-06-12 10:35 UTC, reneradoi commented on DEVELOPMENT.md
> +    juju run redis-k8s/0 get-initial-admin-password --wait
done

2024-06-12 11:31 UTC, Mehdi-Bendriss approved these changes

2024-06-12 11:51 UTC, merged