[DPE-2097] Trigger relation changed when pod get restarted
canonical/redis-k8s-operator pull request #67
Opened 2023-06-08 15:25 UTC by arturo-seijas

In the event of a pod restart on the same node the upgrade event is not fired. The IP might change, so the data needs to be propagated

2023-06-08 16:08 UTC, delgod requested changes

2023-06-08 16:08 UTC, delgod commented on src/charm.py
> +                self.unit_pod_hostname
I think it is more correct to put leader IP
```suggestion
                self.current_master
```

2023-06-08 16:12 UTC, zmraul commented on src/charm.py
> +                self.unit_pod_hostname
Good catch! Yes, you need to announce the IP using `current_master`. Same as here: https://github.com/canonical/redis-k8s-operator/blob/5b796003e0e99a6ecdd4fd64b83f4c6cc1102e2e/lib/charms/redis_k8s/v0/redis.py#L103

2023-06-12 17:10 UTC, delgod approved these changes

2023-06-12 20:13 UTC, zmraul approved these changes

2023-06-14 14:56 UTC, merged