Fix integration tests
canonical/redis-k8s-operator pull request #68
Opened 2023-06-09 06:51 UTC by zmraul

2023-06-13 12:17 UTC, arturo-seijas approved these changes
LGTM

2023-06-13 16:43 UTC, delgod requested changes

2023-06-13 16:43 UTC, delgod commented on tests/integration/test_scaling.py
> +    time.sleep(10)
I think HA should work fine without these lines

2023-06-13 16:47 UTC, deusebio approved these changes
LGTM

2023-06-13 17:15 UTC, zmraul commented on tests/integration/test_scaling.py
> +    time.sleep(10)
The issue seems to happen because of timing on sentinel side apparently, but Redis does update the primary. This is checked on the [relation tests here](https://github.com/canonical/redis-k8s-operator/pull/68/files#diff-1d7a38961d1e0695f63f1958ae253a1228160723122667bb47c158042971e30bR124), where the primary pod is deleted while being related to discourse.

2023-06-14 10:17 UTC, delgod approved these changes

2023-06-14 10:32 UTC, merged