Replace current_master for current_primary
canonical/redis-k8s-operator pull request #78
Opened 2024-02-20 16:08 UTC by amandahla

## Issue
Charms using the Redis library that check for inclusive naming fail because of the word "master".

## Solution
Replace current_master for current_primary

2024-02-21 09:56 UTC, mthaddon commented on lib/charms/redis_k8s/v0/redis.py
> +    def _get_main_ip(self) -> str:
I think "primary" might be more appropriate that "main" here? What do you think? (Same comment for all other changes too if we chose to go that route)

2024-02-21 10:25 UTC, zmraul reviewed
This was done because Redis uses a "master-replica" naming scheme.

I would probably avoid changing it on a couple of places related to the lib, and then having the same concept still called "master" all over the charm. In any case, as Tom pointed out, `primary` is the more common name.

2024-02-21 12:55 UTC, amandahla commented
I changed only the part related to the library because I was afraid of causing a big impact/too much to review.
I'll change it for primary!

2024-02-21 13:19 UTC, amandahla commented on lib/charms/redis_k8s/v0/redis.py
> +    def _get_main_ip(self) -> str:
Nice, changed to primary, thanks

2024-02-21 13:39 UTC, amandahla commented
@zmraul I changed everything now

2024-02-22 12:22 UTC, delgod commented
@amandahla, a huge thank you for the contribution! Really

Could you please make sure that the charm actually works after the changes?
also, could you make all the tests work?
We cannot merge PR with broken tests or code

2024-02-22 12:54 UTC, zmraul requested changes
Thanks for the changes!

I'm not a 100% sure that I caught them all, but please do not change commands or outputs from commands sent/received from Redis or Sentinel.

2024-02-22 12:54 UTC, zmraul commented on src/sentinel.py
> +                primary_info = sentinel.execute_command(f"SENTINEL primary {self.charm._name}")
This command needs to stay as `SENTINEL master`

2024-02-22 12:54 UTC, zmraul commented on tests/integration/test_charm.py
> +    sentinels_connected = sentinel.info("sentinel")["primary0"]["sentinels"]
This needs to stay as `master0` as it's the output of a sentinel command.

2024-02-22 12:54 UTC, zmraul commented on tests/integration/test_scaling.py
> +        lambda: "failover-status" not in sentinel.execute_command(f"SENTINEL primary {APP_NAME}"),
Keep as `SENTINEL master`

2024-02-22 12:54 UTC, zmraul commented on tests/integration/test_scaling.py
> +    primary_info = sentinel.execute_command(f"SENTINEL primary {APP_NAME}")
Keep as `SENTINEL master`

2024-02-22 12:54 UTC, zmraul commented on tests/integration/test_scaling.py
> +    assert last_redis.execute_command("ROLE")[0] != "primary"
Keep as `master`

2024-02-22 12:54 UTC, zmraul commented on tests/integration/test_scaling.py
> +        lambda: "failover-status" not in sentinel.execute_command(f"SENTINEL primary {APP_NAME}"),
Keep as `SENTINEL master`

2024-02-22 12:54 UTC, zmraul commented on tests/integration/test_scaling.py
> +    assert last_redis.execute_command("ROLE")[0] == "primary"
Keep as `master`

2024-02-22 12:54 UTC, zmraul commented on tests/integration/test_scaling.py
> +    primary_info = sentinel.execute_command(f"SENTINEL primary {APP_NAME}")
Keep as `SENTINEL master`

2024-02-22 12:54 UTC, zmraul commented on tests/unit/test_charm.py
> +            f"--primaryauth {self.harness.charm._get_password()}",
Keep as `--masterauth`

2024-02-22 12:54 UTC, zmraul commented on tests/unit/test_charm.py
> +            f"--primaryauth {self.harness.charm._get_password()}",
Keep as `--masterauth`

2024-02-22 12:54 UTC, zmraul commented on tests/unit/test_charm.py
> +            f"--primaryauth {self.harness.charm._get_password()}",
Keep as `--masterauth`

2024-02-22 12:54 UTC, zmraul commented on tests/unit/test_charm.py
> +                f"SENTINEL primary {self.harness.charm._name}": [
Keep as `SENTINEL master`

2024-02-22 12:54 UTC, zmraul commented on tests/unit/test_charm.py
> +                    "primary",
Keep as `master`

2024-02-22 12:54 UTC, zmraul commented on tests/unit/test_charm.py
> +            f"--primaryauth {self.harness.charm._get_password()}",
Keep as `--masterauth`

2024-02-22 12:54 UTC, zmraul commented on tests/unit/test_charm.py
> +                f"SENTINEL primary {self.harness.charm._name}": [
Keep as `SENTINEL master`

2024-02-22 12:54 UTC, zmraul commented on tests/unit/test_charm.py
> +        # call to `execute_command(SENTINEL primary redis-k8s)` will return `different_leader`
Keep as `SENTINEL master`

2024-02-22 12:54 UTC, zmraul commented on tests/unit/test_charm.py
> +                f"SENTINEL primary {self.harness.charm._name}": [
Keep as `SENTINEL MASTER`

2024-02-22 12:54 UTC, zmraul commented on tests/unit/test_charm.py
> +                    "primary",
Keep as `master`

2024-02-22 12:56 UTC, amandahla commented
> @amandahla, a huge thank you for the contribution! Really
> 
> Could you please make sure that the charm actually works after the changes? also, could you make all the tests work? We cannot merge PR with broken tests or code

Hi, unfortunately I believe the tests are failing for something not related to this PR:
This is setting to use agent version 2.9.43
https://github.com/canonical/redis-k8s-operator/blob/main/.github/workflows/ci.yaml#L42
Error message:
 ERROR this client can only bootstrap 3.3 agents

2024-02-22 13:16 UTC, amandahla commented on src/sentinel.py
> +                primary_info = sentinel.execute_command(f"SENTINEL primary {self.charm._name}")
Fixed.

2024-02-22 13:16 UTC, amandahla commented on tests/integration/test_charm.py
> +    sentinels_connected = sentinel.info("sentinel")["primary0"]["sentinels"]
Fixed.

2024-02-22 13:16 UTC, amandahla commented on tests/integration/test_scaling.py
> +        lambda: "failover-status" not in sentinel.execute_command(f"SENTINEL primary {APP_NAME}"),
Fixed.

2024-02-22 13:16 UTC, amandahla commented on tests/integration/test_scaling.py
> +    primary_info = sentinel.execute_command(f"SENTINEL primary {APP_NAME}")
Fixed.

2024-02-22 13:16 UTC, amandahla commented on tests/integration/test_scaling.py
> +    assert last_redis.execute_command("ROLE")[0] != "primary"
Fixed.

2024-02-22 13:16 UTC, amandahla commented on tests/integration/test_scaling.py
> +        lambda: "failover-status" not in sentinel.execute_command(f"SENTINEL primary {APP_NAME}"),
Fixed.

2024-02-22 13:16 UTC, amandahla commented on tests/integration/test_scaling.py
> +    assert last_redis.execute_command("ROLE")[0] == "primary"
Fixed.

2024-02-22 13:16 UTC, amandahla commented on tests/integration/test_scaling.py
> +    primary_info = sentinel.execute_command(f"SENTINEL primary {APP_NAME}")
Fixed.

2024-02-22 13:16 UTC, amandahla commented on tests/unit/test_charm.py
> +            f"--primaryauth {self.harness.charm._get_password()}",
Fixed.

2024-02-22 13:17 UTC, amandahla commented on tests/unit/test_charm.py
> +            f"--primaryauth {self.harness.charm._get_password()}",
Fixed.

2024-02-22 13:17 UTC, amandahla commented on tests/unit/test_charm.py
> +            f"--primaryauth {self.harness.charm._get_password()}",
Fixed.

2024-02-22 13:17 UTC, amandahla commented on tests/unit/test_charm.py
> +                f"SENTINEL primary {self.harness.charm._name}": [
Fixed.

2024-02-22 13:17 UTC, amandahla commented on tests/unit/test_charm.py
> +                    "primary",
Fixed.

2024-02-22 13:17 UTC, amandahla commented on tests/unit/test_charm.py
> +            f"--primaryauth {self.harness.charm._get_password()}",
Fixed.

2024-02-22 13:18 UTC, amandahla commented on tests/unit/test_charm.py
> +                f"SENTINEL primary {self.harness.charm._name}": [
Fixed.

2024-02-22 13:18 UTC, amandahla commented on tests/unit/test_charm.py
> +        # call to `execute_command(SENTINEL primary redis-k8s)` will return `different_leader`
Fixed.

2024-02-22 13:18 UTC, amandahla commented on tests/unit/test_charm.py
> +                f"SENTINEL primary {self.harness.charm._name}": [
Fixed.

2024-02-22 13:18 UTC, amandahla commented on tests/unit/test_charm.py
> +                    "primary",
Fixed.

2024-02-22 14:32 UTC, amandahla commented
> @amandahla, a huge thank you for the contribution! Really
> 
> Could you please make sure that the charm actually works after the changes? also, could you make all the tests work? We cannot merge PR with broken tests or code
@delgod 
I give it a try anyway but no deal:
https://github.com/canonical/redis-k8s-operator/actions/runs/8005322711/job/21864500948?pr=78

2024-02-23 12:05 UTC, zmraul requested changes
Thanks! 
I'll take a look failures when I have a moment, as they seem unrelated to the charm itself.

2024-02-23 12:05 UTC, zmraul commented on lib/charms/redis_k8s/v0/redis.py
`LIBPATCH` on the lib will need updating to 6

2024-04-17 07:43 UTC, zmraul commented
Hi @amandahla. Recent changes should fix the CI/tests. Please rebase on main and give it another try!

For the conflicting file, `ci.yaml`, the changes on main should be kept.

2025-11-05 11:10 UTC, amandahla commented
Closing since is not needed anymore.

2025-11-05 11:10 UTC, closed without merging